Repository sanders41/sas7bdat-converter, pull requests merged in 2022-10, with the labels that each got.

#269 Bump mypy pre-commit hook
  .pre-commit-config.yaml
Labels: dependencies, skip-changelog

#270 Loosen requirements
  poetry.lock
  pyproject.toml
Labels: dependencies

#272 Parquet converter
  .github/workflows/tests.yaml
  CONTRIBUTING.md
  README.md
  poetry.lock
  pyproject.toml
  sas7bdat_converter/converter.py
  tests/assets/expected_files/file1.parquet
  tests/assets/expected_files/file2.parquet
  tests/assets/expected_files/file3.parquet
  tests/assets/expected_xpt/file1.parquet
  tests/assets/expected_xpt/file2.parquet
  tests/test_sas7bdat_converter.py
  tox.ini
Labels: enhancement

#276 Bump version for release
  pyproject.toml
  sas7bdat_converter/__init__.py
Labels: skip-changelog

#278 Update lock file
  poetry.lock
Labels: skip-changelog
